export const Paths = {
	root: "/",
	authLogin: "/auth/login",
	authRegister: "/auth/register",
	forgotPassword: "/user/forgot-password",
	aboutUs: "/single/about",
	faq: "/single/faq",
	contact: "/single/contact",
	privacyPolicy: "/single/privacy-policy",
	termsConditions: "/single/terms-conditions",
	awardsRecognition: "/single/awards-recognition",
	shippingDelivery: "/single/shipping-delivery",
	productShop: "/products",
	dashboard: "/user/dashboard",
	BasicInformation: "/user/dashboard/basic-info",
	ordersHistory: "/user/dashboard/orders-history",
	security: "/user/dashboard/security",
	myOrders: "/order/my-orders",
	shopLanding: "/shop",
	campaign: "/campaign",
	checkout: "/checkout",
}
